import type { QuestDefinition } from '@engine/types/quest';

export const chapter1CaravanToHugenUmQuestRegistry: Record<string, QuestDefinition> = {
  mq_survive: {
    id: 'mq_survive',
    title: 'Вижити',
    category: 'main',
    pinned: true,
    description: 'Пережити дорогу до Гуген-Уму, не вмерши від голоду, насильства чи занадто низької безпеки.',
  },
  mq_road_to_hugen_um: {
    id: 'mq_road_to_hugen_um',
    title: 'Дістатися Гуген-Уму',
    category: 'main',
    pinned: true,
    hasProgressBar: true,
    maxProgress: 100,
    description: 'Караван іде підземними й нижніми маршрутами до занепалої столиці Гуген-Уму.',
  },
  mq_what_are_you_to_caravan: {
    id: 'mq_what_are_you_to_caravan',
    title: 'Чим ти станеш для каравану',
    category: 'main',
    pinned: true,
    description:
      'Караван поступово визначає, ким є Мірелла: тягарем, товаром, корисною, небезпечною чи чиєюсь інвестицією.',
  },
  cq_yarva_not_burden: {
    id: 'cq_yarva_not_burden',
    title: 'Не тягар',
    category: 'character',
    ownerId: 'yarva',
    kind: 'persistent',
    description: 'Ярва дає Міреллі обмежений термін довести, що вона не зайве тіло.',
  },
  cq_yarva_three_nights: {
    id: 'cq_yarva_three_nights',
    title: 'Три ночі Ярви',
    category: 'character',
    ownerId: 'yarva',
    kind: 'persistent',
    hasProgressBar: true,
    maxProgress: 3,
    description: 'Три окремі нічні перевірки на корисність, мовчання і стійкість.',
  },
  cq_rashek_before_tract: {
    id: 'cq_rashek_before_tract',
    title: 'Перед трактом',
    category: 'character',
    ownerId: 'rashek',
    kind: 'persistent',
    description: 'Підготовка каравану до виходу на прямий тракт і до того, що може чекати попереду.',
  },
  cq_khazruk_unwritten: {
    id: 'cq_khazruk_unwritten',
    title: 'Те, що не записують',
    category: 'character',
    ownerId: 'khazruk',
    kind: 'branching',
    description: 'Передати або сховати річ, яка не має проходити через офіційний облік.',
  },
  cq_khazruk_pretty_for_filth: {
    id: 'cq_khazruk_pretty_for_filth',
    title: 'Гарна річ для брудної людини',
    category: 'character',
    ownerId: 'khazruk',
    kind: 'branching',
    description: 'Хазрук пропонує чистоту, тканину або дрібну форму в обмін на негрошову ціну.',
  },
  cq_khazruk_invest: {
    id: 'cq_khazruk_invest',
    title: 'Вкластися в тебе',
    category: 'character',
    ownerId: 'khazruk',
    kind: 'persistent',
    description: 'Хазрук починає робити з Мірелли проєкт, якщо бачить у цьому прибуток.',
  },
  cq_liena_do_not_look: {
    id: 'cq_liena_do_not_look',
    title: 'Не дивися на мене так',
    category: 'character',
    ownerId: 'liena',
    kind: 'persistent',
    description: 'Лієна не витримує погляду Мірелли, бо бачить у ньому власне падіння.',
  },
  cq_salver_trading_daughter: {
    id: 'cq_salver_trading_daughter',
    title: 'Батько, що торгується',
    category: 'character',
    ownerId: 'salver',
    kind: 'branching',
    description: 'Салвер готовий обміняти дочку на шанс дотягнути до міста.',
  },
  cq_tail_entry: {
    id: 'cq_tail_entry',
    title: 'Вхід у хвіст',
    category: 'character',
    ownerId: 'nadra',
    kind: 'persistent',
    description: 'Мірелла потрапляє в мутантський хвіст каравану й відкриває нижні способи виживання.',
  },
  cq_black_water: {
    id: 'cq_black_water',
    title: 'Чорна вода',
    category: 'character',
    ownerId: 'nadra',
    kind: 'persistent',
    hasProgressBar: true,
    maxProgress: 2,
    description: 'Відкриває механіку підземної рибалки та нові джерела їжі.',
  },
  cq_not_dead_floating: {
    id: 'cq_not_dead_floating',
    title: 'Те, що плаває не мертвим',
    category: 'character',
    ownerId: 'krivozub',
    kind: 'episodic',
    description:
      'Під час рибалки або біля чорної води Мірелла знаходить щось дивне, не схоже на звичайний улов.',
  },
  cq_voice_from_tail: {
    id: 'cq_voice_from_tail',
    title: 'Хтось із хвоста чув',
    category: 'character',
    ownerId: 'sivra',
    kind: 'persistent',
    description: 'Чутка або попередження про те, що попереду на тракті щось не так.',
  },
  cq_rumor_by_evening: {
    id: 'cq_rumor_by_evening',
    title: 'Чутка до вечора',
    category: 'daily',
    ownerId: 'sivra',
    kind: 'daily',
    description: 'Розкрутити, перенаправити або вбити потрібну чутку до кінця дня.',
  },
  cq_salt_pass: {
    id: 'cq_salt_pass',
    title: 'Соляний прохід',
    category: 'character',
    ownerId: 'rashek',
    kind: 'persistent',
    description: 'Небезпечний маршрут, де дорога, бій і ресурси злипаються в одну проблему.',
  },
  cq_not_like_others: {
    id: 'cq_not_like_others',
    title: 'Не така',
    category: 'character',
    ownerId: 'yarva',
    kind: 'episodic',
    description: 'У каравані хтось стає мішенню підозри як «не такий».',
  },
  cq_dress_for_food: {
    id: 'cq_dress_for_food',
    title: 'Сукня для їжі',
    category: 'character',
    ownerId: 'khazruk',
    kind: 'episodic',
    description: 'Частину старої форми або приниження в красивій оболонці пропонують обміняти на ресурси.',
  },
};
