import type { QuestDefinition } from '@engine/types/quest';

export const chapter1CaravanToHugenUmQuestRegistry: Record<string, QuestDefinition> = {
  mq_survive: {
    id: 'mq_survive',
    title: 'Р’РёР¶РёС‚Рё',
    category: 'main',
    pinned: true,
    description: 'РџРµСЂРµР¶РёС‚Рё РґРѕСЂРѕРіСѓ РґРѕ Р“СѓРіРµРЅ-РЈРјСѓ, РЅРµ РІРјРµСЂС€Рё РІС–Рґ РіРѕР»РѕРґСѓ, РЅР°СЃРёР»СЊСЃС‚РІР° С‡Рё Р·Р°РЅР°РґС‚Рѕ РЅРёР·СЊРєРѕС— Р±РµР·РїРµРєРё.',
  },
  mq_road_to_hugen_um: {
    id: 'mq_road_to_hugen_um',
    title: 'Р”С–СЃС‚Р°С‚РёСЃСЏ Р“СѓРіРµРЅ-РЈРјСѓ',
    category: 'main',
    pinned: true,
    hasProgressBar: true,
    maxProgress: 100,
    description: 'РљР°СЂР°РІР°РЅ С–РґРµ РїС–РґР·РµРјРЅРёРјРё Р№ РЅРёР¶РЅС–РјРё РјР°СЂС€СЂСѓС‚Р°РјРё РґРѕ Р·Р°РЅРµРїР°Р»РѕС— СЃС‚РѕР»РёС†С– Р“СѓРіРµРЅ-РЈРјСѓ.',
  },
  mq_what_are_you_to_caravan: {
    id: 'mq_what_are_you_to_caravan',
    title: 'Р§РёРј С‚Рё СЃС‚Р°РЅРµС€ РґР»СЏ РєР°СЂР°РІР°РЅСѓ',
    category: 'main',
    pinned: true,
    description:
      'РљР°СЂР°РІР°РЅ РїРѕСЃС‚СѓРїРѕРІРѕ РІРёР·РЅР°С‡Р°С”, РєРёРј С” РњС–СЂРµР»Р»Р°: С‚СЏРіР°СЂРµРј, С‚РѕРІР°СЂРѕРј, РєРѕСЂРёСЃРЅРѕСЋ, РЅРµР±РµР·РїРµС‡РЅРѕСЋ С‡Рё С‡РёС”СЋСЃСЊ С–РЅРІРµСЃС‚РёС†С–С”СЋ.',
    stages: [
      {
        id: 'caravan-first-impression',
        title: 'First impressions',
        description: 'The caravan starts reading Mirella as someone with real leverage.',
        objectives: [
          {
            id: 'yarva-trust',
            label: 'Earn at least a little trust from Yarva.',
            kind: 'condition',
            conditions: [{ type: 'relationship', relationshipId: 'yarva', axis: 'trust', operator: 'gte', value: 1 }],
          },
        ],
        nextStageId: 'caravan-visible-value',
      },
      {
        id: 'caravan-visible-value',
        title: 'Visible value',
        description: 'The caravan begins seeing concrete value in keeping Mirella close.',
        objectives: [
          {
            id: 'morale-holds',
            label: 'Keep caravan morale from collapsing.',
            kind: 'condition',
            conditions: [{ type: 'meta', key: 'morale', operator: 'gte', value: 1 }],
          },
        ],
      },
    ],
  },
  cq_yarva_not_burden: {
    id: 'cq_yarva_not_burden',
    title: 'РќРµ С‚СЏРіР°СЂ',
    category: 'character',
    ownerId: 'yarva',
    kind: 'persistent',
    description: 'РЇСЂРІР° РґР°С” РњС–СЂРµР»Р»С– РѕР±РјРµР¶РµРЅРёР№ С‚РµСЂРјС–РЅ РґРѕРІРµСЃС‚Рё, С‰Рѕ РІРѕРЅР° РЅРµ Р·Р°Р№РІРµ С‚С–Р»Рѕ.',
  },
  cq_yarva_three_nights: {
    id: 'cq_yarva_three_nights',
    title: 'РўСЂРё РЅРѕС‡С– РЇСЂРІРё',
    category: 'character',
    ownerId: 'yarva',
    kind: 'persistent',
    hasProgressBar: true,
    maxProgress: 3,
    description: 'РўСЂРё РѕРєСЂРµРјС– РЅС–С‡РЅС– РїРµСЂРµРІС–СЂРєРё РЅР° РєРѕСЂРёСЃРЅС–СЃС‚СЊ, РјРѕРІС‡Р°РЅРЅСЏ С– СЃС‚С–Р№РєС–СЃС‚СЊ.',
    stages: [
      {
        id: 'night-one',
        title: 'Night one',
        description: 'Survive Yarva`s first private test.',
        objectives: [
          {
            id: 'night-one-complete',
            label: 'Endure the first night.',
            kind: 'counter',
            targetValue: 1,
          },
        ],
        nextStageId: 'night-two',
      },
      {
        id: 'night-two',
        title: 'Night two',
        description: 'Hold your composure through the second night.',
        objectives: [
          {
            id: 'night-two-complete',
            label: 'Endure the second night.',
            kind: 'counter',
            targetValue: 1,
          },
        ],
        nextStageId: 'night-three',
      },
      {
        id: 'night-three',
        title: 'Night three',
        description: 'The last proof that Mirella is still useful to Yarva.',
        objectives: [
          {
            id: 'night-three-complete',
            label: 'Endure the third night.',
            kind: 'counter',
            targetValue: 1,
          },
        ],
      },
    ],
  },
  cq_rashek_before_tract: {
    id: 'cq_rashek_before_tract',
    title: 'РџРµСЂРµРґ С‚СЂР°РєС‚РѕРј',
    category: 'character',
    ownerId: 'rashek',
    kind: 'persistent',
    description: 'РџС–РґРіРѕС‚РѕРІРєР° РєР°СЂР°РІР°РЅСѓ РґРѕ РІРёС…РѕРґСѓ РЅР° РїСЂСЏРјРёР№ С‚СЂР°РєС‚ С– РґРѕ С‚РѕРіРѕ, С‰Рѕ РјРѕР¶Рµ С‡РµРєР°С‚Рё РїРѕРїРµСЂРµРґСѓ.',
  },
  cq_khazruk_unwritten: {
    id: 'cq_khazruk_unwritten',
    title: 'РўРµ, С‰Рѕ РЅРµ Р·Р°РїРёСЃСѓСЋС‚СЊ',
    category: 'character',
    ownerId: 'khazruk',
    kind: 'branching',
    description: 'РџРµСЂРµРґР°С‚Рё Р°Р±Рѕ СЃС…РѕРІР°С‚Рё СЂС–С‡, СЏРєР° РЅРµ РјР°С” РїСЂРѕС…РѕРґРёС‚Рё С‡РµСЂРµР· РѕС„С–С†С–Р№РЅРёР№ РѕР±Р»С–Рє.',
  },
  cq_khazruk_pretty_for_filth: {
    id: 'cq_khazruk_pretty_for_filth',
    title: 'Р“Р°СЂРЅР° СЂС–С‡ РґР»СЏ Р±СЂСѓРґРЅРѕС— Р»СЋРґРёРЅРё',
    category: 'character',
    ownerId: 'khazruk',
    kind: 'branching',
    description: 'РҐР°Р·СЂСѓРє РїСЂРѕРїРѕРЅСѓС” С‡РёСЃС‚РѕС‚Сѓ, С‚РєР°РЅРёРЅСѓ Р°Р±Рѕ РґСЂС–Р±РЅСѓ С„РѕСЂРјСѓ РІ РѕР±РјС–РЅ РЅР° РЅРµРіСЂРѕС€РѕРІСѓ С†С–РЅСѓ.',
  },
  cq_khazruk_invest: {
    id: 'cq_khazruk_invest',
    title: 'Р’РєР»Р°СЃС‚РёСЃСЏ РІ С‚РµР±Рµ',
    category: 'character',
    ownerId: 'khazruk',
    kind: 'persistent',
    description: 'РҐР°Р·СЂСѓРє РїРѕС‡РёРЅР°С” СЂРѕР±РёС‚Рё Р· РњС–СЂРµР»Р»Рё РїСЂРѕС”РєС‚, СЏРєС‰Рѕ Р±Р°С‡РёС‚СЊ Сѓ С†СЊРѕРјСѓ РїСЂРёР±СѓС‚РѕРє.',
  },
  cq_liena_do_not_look: {
    id: 'cq_liena_do_not_look',
    title: 'РќРµ РґРёРІРёСЃСЏ РЅР° РјРµРЅРµ С‚Р°Рє',
    category: 'character',
    ownerId: 'liena',
    kind: 'persistent',
    description: 'Р›С–С”РЅР° РЅРµ РІРёС‚СЂРёРјСѓС” РїРѕРіР»СЏРґСѓ РњС–СЂРµР»Р»Рё, Р±Рѕ Р±Р°С‡РёС‚СЊ Сѓ РЅСЊРѕРјСѓ РІР»Р°СЃРЅРµ РїР°РґС–РЅРЅСЏ.',
  },
  cq_salver_trading_daughter: {
    id: 'cq_salver_trading_daughter',
    title: 'Р‘Р°С‚СЊРєРѕ, С‰Рѕ С‚РѕСЂРіСѓС”С‚СЊСЃСЏ',
    category: 'character',
    ownerId: 'salver',
    kind: 'branching',
    description: 'РЎР°Р»РІРµСЂ РіРѕС‚РѕРІРёР№ РѕР±РјС–РЅСЏС‚Рё РґРѕС‡РєСѓ РЅР° С€Р°РЅСЃ РґРѕС‚СЏРіРЅСѓС‚Рё РґРѕ РјС–СЃС‚Р°.',
  },
  cq_tail_entry: {
    id: 'cq_tail_entry',
    title: 'Р’С…С–Рґ Сѓ С…РІС–СЃС‚',
    category: 'character',
    ownerId: 'nadra',
    kind: 'persistent',
    description: 'РњС–СЂРµР»Р»Р° РїРѕС‚СЂР°РїР»СЏС” РІ РјСѓС‚Р°РЅС‚СЃСЊРєРёР№ С…РІС–СЃС‚ РєР°СЂР°РІР°РЅСѓ Р№ РІС–РґРєСЂРёРІР°С” РЅРёР¶РЅС– СЃРїРѕСЃРѕР±Рё РІРёР¶РёРІР°РЅРЅСЏ.',
  },
  cq_black_water: {
    id: 'cq_black_water',
    title: 'Р§РѕСЂРЅР° РІРѕРґР°',
    category: 'character',
    ownerId: 'nadra',
    kind: 'persistent',
    hasProgressBar: true,
    maxProgress: 2,
    description: 'Р’С–РґРєСЂРёРІР°С” РјРµС…Р°РЅС–РєСѓ РїС–РґР·РµРјРЅРѕС— СЂРёР±Р°Р»РєРё С‚Р° РЅРѕРІС– РґР¶РµСЂРµР»Р° С—Р¶С–.',
  },
  cq_not_dead_floating: {
    id: 'cq_not_dead_floating',
    title: 'РўРµ, С‰Рѕ РїР»Р°РІР°С” РЅРµ РјРµСЂС‚РІРёРј',
    category: 'character',
    ownerId: 'krivozub',
    kind: 'episodic',
    description:
      'РџС–Рґ С‡Р°СЃ СЂРёР±Р°Р»РєРё Р°Р±Рѕ Р±С–Р»СЏ С‡РѕСЂРЅРѕС— РІРѕРґРё РњС–СЂРµР»Р»Р° Р·РЅР°С…РѕРґРёС‚СЊ С‰РѕСЃСЊ РґРёРІРЅРµ, РЅРµ СЃС…РѕР¶Рµ РЅР° Р·РІРёС‡Р°Р№РЅРёР№ СѓР»РѕРІ.',
  },
  cq_voice_from_tail: {
    id: 'cq_voice_from_tail',
    title: 'РҐС‚РѕСЃСЊ С–Р· С…РІРѕСЃС‚Р° С‡СѓРІ',
    category: 'character',
    ownerId: 'sivra',
    kind: 'persistent',
    description: 'Р§СѓС‚РєР° Р°Р±Рѕ РїРѕРїРµСЂРµРґР¶РµРЅРЅСЏ РїСЂРѕ С‚Рµ, С‰Рѕ РїРѕРїРµСЂРµРґСѓ РЅР° С‚СЂР°РєС‚С– С‰РѕСЃСЊ РЅРµ С‚Р°Рє.',
  },
  cq_rumor_by_evening: {
    id: 'cq_rumor_by_evening',
    title: 'Р§СѓС‚РєР° РґРѕ РІРµС‡РѕСЂР°',
    category: 'daily',
    ownerId: 'sivra',
    kind: 'daily',
    description: 'Р РѕР·РєСЂСѓС‚РёС‚Рё, РїРµСЂРµРЅР°РїСЂР°РІРёС‚Рё Р°Р±Рѕ РІР±РёС‚Рё РїРѕС‚СЂС–Р±РЅСѓ С‡СѓС‚РєСѓ РґРѕ РєС–РЅС†СЏ РґРЅСЏ.',
  },
  cq_salt_pass: {
    id: 'cq_salt_pass',
    title: 'РЎРѕР»СЏРЅРёР№ РїСЂРѕС…С–Рґ',
    category: 'character',
    ownerId: 'rashek',
    kind: 'persistent',
    description: 'РќРµР±РµР·РїРµС‡РЅРёР№ РјР°СЂС€СЂСѓС‚, РґРµ РґРѕСЂРѕРіР°, Р±С–Р№ С– СЂРµСЃСѓСЂСЃРё Р·Р»РёРїР°СЋС‚СЊСЃСЏ РІ РѕРґРЅСѓ РїСЂРѕР±Р»РµРјСѓ.',
  },
  cq_not_like_others: {
    id: 'cq_not_like_others',
    title: 'РќРµ С‚Р°РєР°',
    category: 'character',
    ownerId: 'yarva',
    kind: 'episodic',
    description: 'РЈ РєР°СЂР°РІР°РЅС– С…С‚РѕСЃСЊ СЃС‚Р°С” РјС–С€РµРЅРЅСЋ РїС–РґРѕР·СЂРё СЏРє В«РЅРµ С‚Р°РєРёР№В».',
  },
  cq_dress_for_food: {
    id: 'cq_dress_for_food',
    title: 'РЎСѓРєРЅСЏ РґР»СЏ С—Р¶С–',
    category: 'character',
    ownerId: 'khazruk',
    kind: 'episodic',
    description: 'Р§Р°СЃС‚РёРЅСѓ СЃС‚Р°СЂРѕС— С„РѕСЂРјРё Р°Р±Рѕ РїСЂРёРЅРёР¶РµРЅРЅСЏ РІ РєСЂР°СЃРёРІС–Р№ РѕР±РѕР»РѕРЅС†С– РїСЂРѕРїРѕРЅСѓСЋС‚СЊ РѕР±РјС–РЅСЏС‚Рё РЅР° СЂРµСЃСѓСЂСЃРё.',
  },
};
