import type { QuestDefinition } from '@engine/types/quest';

export const chapter2HugenUmQuestRegistry: Record<string, QuestDefinition> = {
  mq_survive_hugen_um: {
    id: 'mq_survive_hugen_um',
    title: 'Не зникнути в Гуген-Умі',
    category: 'main',
    pinned: true,
    description: 'Пережити перші дні в місті, яке сортує приїжджих на корисних, продажних і зайвих.',
  },
  mq_become_unremovable: {
    id: 'mq_become_unremovable',
    title: 'Стати незнімною',
    category: 'main',
    pinned: true,
    hasProgressBar: true,
    maxProgress: 3,
    description: 'Знайти в міському механізмі місце, з якого Міреллу вже не зможуть просто виштовхнути.',
  },
  mq_whose_name_holds_you: {
    id: 'mq_whose_name_holds_you',
    title: 'Чиє ім’я тримає тебе',
    category: 'main',
    pinned: true,
    hasProgressBar: true,
    maxProgress: 2,
    description: 'Зрозуміти, чи тримає Міреллу її власне ім’я, караванний слід, міська мітка чи чужий борг.',
  },
  cq_vey_ledger_mark: {
    id: 'cq_vey_ledger_mark',
    title: 'Мітка в реєстрі',
    category: 'character',
    ownerId: 'registrar-vey',
    kind: 'persistent',
    description: 'Реєстратор Вей вносить Міреллу до міських книг і цим визначає, як на неї дивитимуться брама, суд і ринок.',
  },
  cq_nena_first_deal: {
    id: 'cq_nena_first_deal',
    title: 'Перший міський борг',
    category: 'character',
    ownerId: 'broker-nena',
    kind: 'branching',
    hasProgressBar: true,
    maxProgress: 2,
    description: 'Нена намагається зробити з Мірелли корисну ланку між ринком, притулком і судовим передпокоєм.',
  },
  cq_ioma_bed_without_name: {
    id: 'cq_ioma_bed_without_name',
    title: 'Ліжко без імені',
    category: 'character',
    ownerId: 'matron-ioma',
    kind: 'persistent',
    description: 'Іома може дати місце для сну, але не дає його тим, хто не готовий чимось заплатити.',
  },
  cq_rusk_tail_entry: {
    id: 'cq_rusk_tail_entry',
    title: 'Вхід у хвостовий квартал',
    category: 'character',
    ownerId: 'tail-keeper-rusk',
    kind: 'persistent',
    description: 'Руск вирішує, чи вважають Міреллу гостею, тінню чи ресурсом нижчого міського хвоста.',
  },
  cq_sivra_rumor_chain: {
    id: 'cq_sivra_rumor_chain',
    title: 'Міський ланцюг чуток',
    category: 'character',
    ownerId: 'sivra',
    kind: 'persistent',
    description: 'Сівра відчуває, як караванні чутки вростають у міську систему продажу, суду і страху.',
  },
};
