import type { QuestDefinition } from '@engine/types/quest';

export const chapter2HugenUmQuestRegistry: Record<string, QuestDefinition> = {
  mq_survive_hugen_um: {
    id: 'mq_survive_hugen_um',
    title: 'РќРµ Р·РЅРёРєРЅСѓС‚Рё РІ Р“СѓРіРµРЅ-РЈРјС–',
    category: 'main',
    pinned: true,
    description: 'РџРµСЂРµР¶РёС‚Рё РїРµСЂС€С– РґРЅС– РІ РјС–СЃС‚С–, СЏРєРµ СЃРѕСЂС‚СѓС” РїСЂРёС—Р¶РґР¶РёС… РЅР° РєРѕСЂРёСЃРЅРёС…, РїСЂРѕРґР°Р¶РЅРёС… С– Р·Р°Р№РІРёС….',
  },
  mq_become_unremovable: {
    id: 'mq_become_unremovable',
    title: 'РЎС‚Р°С‚Рё РЅРµР·РЅС–РјРЅРѕСЋ',
    category: 'main',
    pinned: true,
    hasProgressBar: true,
    maxProgress: 3,
    description: 'Р—РЅР°Р№С‚Рё РІ РјС–СЃСЊРєРѕРјСѓ РјРµС…Р°РЅС–Р·РјС– РјС–СЃС†Рµ, Р· СЏРєРѕРіРѕ РњС–СЂРµР»Р»Сѓ РІР¶Рµ РЅРµ Р·РјРѕР¶СѓС‚СЊ РїСЂРѕСЃС‚Рѕ РІРёС€С‚РѕРІС…РЅСѓС‚Рё.',
  },
  mq_whose_name_holds_you: {
    id: 'mq_whose_name_holds_you',
    title: 'Р§РёС” С–РјвЂ™СЏ С‚СЂРёРјР°С” С‚РµР±Рµ',
    category: 'main',
    pinned: true,
    hasProgressBar: true,
    maxProgress: 2,
    description: 'Р—СЂРѕР·СѓРјС–С‚Рё, С‡Рё С‚СЂРёРјР°С” РњС–СЂРµР»Р»Сѓ С—С— РІР»Р°СЃРЅРµ С–РјвЂ™СЏ, РєР°СЂР°РІР°РЅРЅРёР№ СЃР»С–Рґ, РјС–СЃСЊРєР° РјС–С‚РєР° С‡Рё С‡СѓР¶РёР№ Р±РѕСЂРі.',
  },
  cq_vey_ledger_mark: {
    id: 'cq_vey_ledger_mark',
    title: 'РњС–С‚РєР° РІ СЂРµС”СЃС‚СЂС–',
    category: 'character',
    ownerId: 'registrar-vey',
    kind: 'persistent',
    description: 'Р РµС”СЃС‚СЂР°С‚РѕСЂ Р’РµР№ РІРЅРѕСЃРёС‚СЊ РњС–СЂРµР»Р»Сѓ РґРѕ РјС–СЃСЊРєРёС… РєРЅРёРі С– С†РёРј РІРёР·РЅР°С‡Р°С”, СЏРє РЅР° РЅРµС— РґРёРІРёС‚РёРјСѓС‚СЊСЃСЏ Р±СЂР°РјР°, СЃСѓРґ С– СЂРёРЅРѕРє.',
  },
  cq_nena_first_deal: {
    id: 'cq_nena_first_deal',
    title: 'РџРµСЂС€РёР№ РјС–СЃСЊРєРёР№ Р±РѕСЂРі',
    category: 'character',
    ownerId: 'broker-nena',
    kind: 'branching',
    hasProgressBar: true,
    maxProgress: 2,
    description: 'РќРµРЅР° РЅР°РјР°РіР°С”С‚СЊСЃСЏ Р·СЂРѕР±РёС‚Рё Р· РњС–СЂРµР»Р»Рё РєРѕСЂРёСЃРЅСѓ Р»Р°РЅРєСѓ РјС–Р¶ СЂРёРЅРєРѕРј, РїСЂРёС‚СѓР»РєРѕРј С– СЃСѓРґРѕРІРёРј РїРµСЂРµРґРїРѕРєРѕС”Рј.',
    stages: [
      {
        id: 'nena-offer',
        title: 'The first offer',
        description: 'Survive the opening shape of Nena`s deal.',
        objectives: [
          {
            id: 'accept-the-hook',
            label: 'Reach the first point of commitment.',
            kind: 'counter',
            targetValue: 1,
          },
        ],
        nextStageId: 'nena-settlement',
      },
      {
        id: 'nena-settlement',
        title: 'Settlement',
        description: 'Push the deal toward a usable arrangement.',
        objectives: [
          {
            id: 'seal-the-first-deal',
            label: 'Resolve the first city deal.',
            kind: 'counter',
            targetValue: 1,
          },
        ],
      },
    ],
  },
  cq_ioma_bed_without_name: {
    id: 'cq_ioma_bed_without_name',
    title: 'Р›С–Р¶РєРѕ Р±РµР· С–РјРµРЅС–',
    category: 'character',
    ownerId: 'matron-ioma',
    kind: 'persistent',
    description: 'Р†РѕРјР° РјРѕР¶Рµ РґР°С‚Рё РјС–СЃС†Рµ РґР»СЏ СЃРЅСѓ, Р°Р»Рµ РЅРµ РґР°С” Р№РѕРіРѕ С‚РёРј, С…С‚Рѕ РЅРµ РіРѕС‚РѕРІРёР№ С‡РёРјРѕСЃСЊ Р·Р°РїР»Р°С‚РёС‚Рё.',
  },
  cq_rusk_tail_entry: {
    id: 'cq_rusk_tail_entry',
    title: 'Р’С…С–Рґ Сѓ С…РІРѕСЃС‚РѕРІРёР№ РєРІР°СЂС‚Р°Р»',
    category: 'character',
    ownerId: 'tail-keeper-rusk',
    kind: 'persistent',
    description: 'Р СѓСЃРє РІРёСЂС–С€СѓС”, С‡Рё РІРІР°Р¶Р°СЋС‚СЊ РњС–СЂРµР»Р»Сѓ РіРѕСЃС‚РµСЋ, С‚С–РЅРЅСЋ С‡Рё СЂРµСЃСѓСЂСЃРѕРј РЅРёР¶С‡РѕРіРѕ РјС–СЃСЊРєРѕРіРѕ С…РІРѕСЃС‚Р°.',
  },
  cq_sivra_rumor_chain: {
    id: 'cq_sivra_rumor_chain',
    title: 'РњС–СЃСЊРєРёР№ Р»Р°РЅС†СЋРі С‡СѓС‚РѕРє',
    category: 'character',
    ownerId: 'sivra',
    kind: 'persistent',
    description: 'РЎС–РІСЂР° РІС–РґС‡СѓРІР°С”, СЏРє РєР°СЂР°РІР°РЅРЅС– С‡СѓС‚РєРё РІСЂРѕСЃС‚Р°СЋС‚СЊ Сѓ РјС–СЃСЊРєСѓ СЃРёСЃС‚РµРјСѓ РїСЂРѕРґР°Р¶Сѓ, СЃСѓРґСѓ С– СЃС‚СЂР°С…Сѓ.',
  },
};
