import type { NarrativeCharacterData } from '@engine/types/narrative';

const chapterId = 'chapter-1';

export const chapter1SupportingCastRegistry: Record<string, NarrativeCharacterData> = {
  mirella: {
    id: 'mirella',
    chapterId,
    displayName: 'Мірелла',
    defaultEmotion: 'neutral',
    defaultPortraitId: 'chapter-1/portraits/mirella/neutral.webp',
    defaultSide: 'center',
    portraitRefs: {
      neutral: 'chapter-1/portraits/mirella/neutral.webp',
      thinking: 'chapter-1/portraits/mirella/thinking.webp',
      serious: 'chapter-1/portraits/mirella/serious.webp',
      polite: 'chapter-1/portraits/mirella/polite.webp',
      curious: 'chapter-1/portraits/mirella/curious.webp',
      shocked: 'chapter-1/portraits/mirella/shocked.webp',
      defiant: 'chapter-1/portraits/mirella/defiant.webp',
      soft: 'chapter-1/portraits/mirella/soft.webp',
      smug: 'chapter-1/portraits/mirella/smug.webp',
      embarrassed: 'chapter-1/portraits/mirella/embarrassed.webp',
      trembling: 'chapter-1/portraits/mirella/trembling.webp',
      broken: 'chapter-1/portraits/mirella/broken.webp',
      hollow: 'chapter-1/portraits/mirella/hollow.webp',
      falling: 'chapter-1/portraits/mirella/falling.webp',
      afraid: 'chapter-1/portraits/mirella/afraid.webp',
      cold: 'chapter-1/portraits/mirella/cold.webp',
      hurt: 'chapter-1/portraits/mirella/hurt.webp',
      humiliated: 'chapter-1/portraits/mirella/humiliated.webp',
    },
  },
  'lady-sera': {
    id: 'lady-sera',
    chapterId,
    displayName: 'Леді Сера',
    defaultEmotion: 'soft',
    defaultPortraitId: 'chapter-1/portraits/lady-sera/soft.webp',
    defaultSide: 'left',
    portraitRefs: {
      soft: 'chapter-1/portraits/lady-sera/soft.webp',
      tired: 'chapter-1/portraits/lady-sera/tired.webp',
      resigned: 'chapter-1/portraits/lady-sera/resigned.webp',
      fragile: 'chapter-1/portraits/lady-sera/fragile.webp',
      sad: 'chapter-1/portraits/lady-sera/sad.webp',
      afraid: 'chapter-1/portraits/lady-sera/afraid.webp',
    },
  },
  'lord-guy': {
    id: 'lord-guy',
    chapterId,
    displayName: 'Лорд Гай',
    defaultEmotion: 'composed',
    defaultPortraitId: 'chapter-1/portraits/lord-guy/composed.webp',
    defaultSide: 'right',
    portraitRefs: {
      composed: 'chapter-1/portraits/lord-guy/composed.webp',
      cold: 'chapter-1/portraits/lord-guy/cold.webp',
      commanding: 'chapter-1/portraits/lord-guy/commanding.webp',
      cruel: 'chapter-1/portraits/lord-guy/cruel.webp',
      amused: 'chapter-1/portraits/lord-guy/amused.webp',
    },
  },
  kael: {
    id: 'kael',
    chapterId,
    displayName: 'Каель',
    defaultEmotion: 'playful',
    defaultPortraitId: 'chapter-1/portraits/kael/playful.webp',
    defaultSide: 'right',
    portraitRefs: {
      playful: 'chapter-1/portraits/kael/playful.webp',
      cocky: 'chapter-1/portraits/kael/cocky.webp',
      nervous: 'chapter-1/portraits/kael/nervous.webp',
    },
  },
  'sir-raust': {
    id: 'sir-raust',
    chapterId,
    displayName: 'Сір Рауст',
    defaultEmotion: 'stern',
    defaultPortraitId: 'chapter-1/portraits/sir-raust/stern.webp',
    defaultSide: 'left',
    portraitRefs: {
      stern: 'chapter-1/portraits/sir-raust/stern.webp',
      grim: 'chapter-1/portraits/sir-raust/grim.webp',
      soft: 'chapter-1/portraits/sir-raust/soft.webp',
      disappointed: 'chapter-1/portraits/sir-raust/disappointed.webp',
      calm: 'chapter-1/portraits/sir-raust/calm.webp',
      protective: 'chapter-1/portraits/sir-raust/protective.webp',
      battle_ready: 'chapter-1/portraits/sir-raust/battle_ready.webp',
    },
  },
  'servant-lyna': {
    id: 'servant-lyna',
    chapterId,
    displayName: 'Ліна',
    defaultEmotion: 'soft',
    defaultPortraitId: 'chapter-1/portraits/servant-lyna/soft.webp',
    defaultSide: 'left',
    portraitRefs: {
      soft: 'chapter-1/portraits/servant-lyna/soft.webp',
      nervous: 'chapter-1/portraits/servant-lyna/nervous.webp',
      embarrassed: 'chapter-1/portraits/servant-lyna/embarrassed.webp',
      serious: 'chapter-1/portraits/servant-lyna/serious.webp',
    },
  },
  'marna-voss': {
    id: 'marna-voss',
    chapterId,
    displayName: 'Марна Восс',
    defaultEmotion: 'professional',
    defaultPortraitId: 'chapter-1/portraits/marna-voss/professional.webp',
    defaultSide: 'left',
    portraitRefs: {
      professional: 'chapter-1/portraits/marna-voss/professional.webp',
      cold: 'chapter-1/portraits/marna-voss/cold.webp',
      sharp: 'chapter-1/portraits/marna-voss/sharp.webp',
      mocking: 'chapter-1/portraits/marna-voss/mocking.webp',
      superior: 'chapter-1/portraits/marna-voss/superior.webp',
    },
  },
  'orc-raider': {
    id: 'orc-raider',
    chapterId,
    displayName: 'Оркоїдний рейдер',
    defaultEmotion: 'dominant',
    defaultPortraitId: 'chapter-1/portraits/orc-raider/dominant.webp',
    defaultSide: 'right',
    portraitRefs: {
      dominant: 'chapter-1/portraits/orc-raider/dominant.webp',
    },
  },
  'old-prisoner': {
    id: 'old-prisoner',
    chapterId,
    displayName: 'Старий в’язень',
    defaultEmotion: 'neutral',
    defaultPortraitId: 'chapter-1/portraits/old-prisoner/neutral.webp',
    defaultSide: 'left',
    portraitRefs: {
      neutral: 'chapter-1/portraits/old-prisoner/neutral.webp',
      shifty: 'chapter-1/portraits/old-prisoner/shifty.webp',
      soft: 'chapter-1/portraits/old-prisoner/soft.webp',
      sad: 'chapter-1/portraits/old-prisoner/sad.webp',
    },
  },
  guard: {
    id: 'guard',
    chapterId,
    displayName: 'Охоронець',
    defaultEmotion: 'cold',
    defaultPortraitId: 'chapter-1/portraits/guard/cold.webp',
    defaultSide: 'right',
    portraitRefs: {
      cold: 'chapter-1/portraits/guard/cold.webp',
    },
  },
  'tessa-grey': {
    id: 'tessa-grey',
    chapterId,
    displayName: 'Тесса Грей',
    defaultEmotion: 'hard',
    defaultPortraitId: 'chapter-1/portraits/tessa-grey/hard.webp',
    defaultSide: 'left',
    portraitRefs: {
      hard: 'chapter-1/portraits/tessa-grey/hard.webp',
    },
  },
  'scarred-woman': {
    id: 'scarred-woman',
    chapterId,
    displayName: 'Шрамована жінка',
    defaultEmotion: 'hateful',
    defaultPortraitId: 'chapter-1/portraits/scarred-woman/hateful.webp',
    defaultSide: 'right',
    portraitRefs: {
      hateful: 'chapter-1/portraits/scarred-woman/hateful.webp',
    },
  },
  'ner-azet': {
    id: 'ner-azet',
    chapterId,
    displayName: 'Нер-Азет',
    defaultEmotion: 'whisper',
    defaultPortraitId: 'chapter-1/portraits/ner-azet/whisper.webp',
    defaultSide: 'left',
    portraitRefs: {
      whisper: 'chapter-1/portraits/ner-azet/whisper.webp',
      hunger: 'chapter-1/portraits/ner-azet/hunger.webp',
      invasion: 'chapter-1/portraits/ner-azet/invasion.webp',
    },
  },
};
