import type { NarrativeCharacterData } from '@engine/types/narrative';

import { mirellaOutfits } from './mirellaOutfits';

const chapterId = 'chapter-1';

export const chapter1SupportingCastRegistry: Record<string, NarrativeCharacterData> = {
  mirella: {
    id: 'mirella',
    chapterId,
    displayName: 'Мірелла',
    role: 'heroine',
    defaultEmotion: 'neutral',
    defaultPortraitId: 'chapter-1/portraits/mirella/neutral.webp',
    defaultSide: 'left',
    defaultOutfitId: 'dress-pristine',
    outfits: mirellaOutfits,
    portraitRefs: {
      neutral: 'chapter-1/portraits/mirella/neutral.webp',
      composed: 'prologue/portraits/mirella/composed.webp',
      waking: 'prologue/portraits/mirella/waking.webp',
      thinking: 'chapter-1/portraits/mirella/thinking.webp',
      distant: 'prologue/portraits/mirella/distant.webp',
      guarded: 'prologue/portraits/mirella/guarded.webp',
      serious: 'chapter-1/portraits/mirella/serious.webp',
      polite: 'chapter-1/portraits/mirella/polite.webp',
      curious: 'chapter-1/portraits/mirella/curious.webp',
      shocked: 'chapter-1/portraits/mirella/shocked.webp',
      defiant: 'chapter-1/portraits/mirella/defiant.webp',
      soft: 'chapter-1/portraits/mirella/soft.webp',
      smug: 'chapter-1/portraits/mirella/smug.webp',
      embarrassed: 'chapter-1/portraits/mirella/embarrassed.webp',
      trembling: 'chapter-1/portraits/mirella/trembling.webp',
      broken: 'chapter-1/portraits/mirella/broken.webp',
      hollow: 'chapter-1/portraits/mirella/hollow.webp',
      falling: 'chapter-1/portraits/mirella/falling.webp',
      afraid: 'chapter-1/portraits/mirella/afraid.webp',
      cold: 'chapter-1/portraits/mirella/cold.webp',
      cool: 'prologue/portraits/mirella/cool.webp',
      shaken: 'prologue/portraits/mirella/shaken.webp',
      hurt: 'chapter-1/portraits/mirella/hurt.webp',
      humiliated: 'chapter-1/portraits/mirella/humiliated.webp',
    },
  },
  father: {
    id: 'father',
    chapterId,
    displayName: 'Батько',
    defaultEmotion: 'cold',
    defaultPortraitId: 'prologue/portraits/father/cold.webp',
    defaultSide: 'left',
    portraitRefs: {
      cold: 'prologue/portraits/father/cold.webp',
    },
  },
  mother: {
    id: 'mother',
    chapterId,
    displayName: 'Мати',
    defaultEmotion: 'tired',
    defaultPortraitId: 'prologue/portraits/mother/tired.webp',
    defaultSide: 'left',
    portraitRefs: {
      tired: 'prologue/portraits/mother/tired.webp',
    },
  },
  aren: {
    id: 'aren',
    chapterId,
    displayName: 'Арен',
    defaultEmotion: 'sharp',
    defaultPortraitId: 'prologue/portraits/aren/sharp.webp',
    defaultSide: 'right',
    portraitRefs: {
      sharp: 'prologue/portraits/aren/sharp.webp',
    },
  },
  edran: {
    id: 'edran',
    chapterId,
    displayName: 'Едран',
    defaultEmotion: 'neutral',
    defaultPortraitId: 'prologue/portraits/edran/neutral.webp',
    defaultSide: 'left',
    portraitRefs: {
      neutral: 'prologue/portraits/edran/neutral.webp',
    },
  },
  servant_girl: {
    id: 'servant_girl',
    chapterId,
    displayName: 'Служниця',
    defaultEmotion: 'careful',
    defaultPortraitId: 'prologue/portraits/servant_girl/careful.webp',
    defaultSide: 'left',
    portraitRefs: {
      careful: 'prologue/portraits/servant_girl/careful.webp',
    },
  },
  grandmother: {
    id: 'grandmother',
    chapterId,
    displayName: 'Бабуся',
    defaultEmotion: 'clear',
    defaultPortraitId: 'prologue/portraits/grandmother/clear.webp',
    defaultSide: 'left',
    portraitRefs: {
      clear: 'prologue/portraits/grandmother/clear.webp',
    },
  },
  'lady-sera': {
    id: 'lady-sera',
    chapterId,
    displayName: 'Леді Сера',
    defaultEmotion: 'soft',
    defaultPortraitId: 'chapter-1/portraits/lady-sera/soft.webp',
    defaultSide: 'left',
    portraitRefs: {
      soft: 'chapter-1/portraits/lady-sera/soft.webp',
      tired: 'chapter-1/portraits/lady-sera/tired.webp',
      resigned: 'chapter-1/portraits/lady-sera/resigned.webp',
      fragile: 'chapter-1/portraits/lady-sera/fragile.webp',
      sad: 'chapter-1/portraits/lady-sera/sad.webp',
      afraid: 'chapter-1/portraits/lady-sera/afraid.webp',
    },
  },
  'lord-guy': {
    id: 'lord-guy',
    chapterId,
    displayName: 'Лорд Гай',
    defaultEmotion: 'composed',
    defaultPortraitId: 'chapter-1/portraits/lord-guy/composed.webp',
    defaultSide: 'right',
    portraitRefs: {
      composed: 'chapter-1/portraits/lord-guy/composed.webp',
      cold: 'chapter-1/portraits/lord-guy/cold.webp',
      commanding: 'chapter-1/portraits/lord-guy/commanding.webp',
      cruel: 'chapter-1/portraits/lord-guy/cruel.webp',
      amused: 'chapter-1/portraits/lord-guy/amused.webp',
    },
  },
  kael: {
    id: 'kael',
    chapterId,
    displayName: 'Каель',
    defaultEmotion: 'playful',
    defaultPortraitId: 'chapter-1/portraits/kael/playful.webp',
    defaultSide: 'right',
    portraitRefs: {
      playful: 'chapter-1/portraits/kael/playful.webp',
      cocky: 'chapter-1/portraits/kael/cocky.webp',
      nervous: 'chapter-1/portraits/kael/nervous.webp',
    },
  },
  'sir-raust': {
    id: 'sir-raust',
    chapterId,
    displayName: 'Сір Рауст',
    defaultEmotion: 'stern',
    defaultPortraitId: 'chapter-1/portraits/sir-raust/stern.webp',
    defaultSide: 'left',
    portraitRefs: {
      stern: 'chapter-1/portraits/sir-raust/stern.webp',
      grim: 'chapter-1/portraits/sir-raust/grim.webp',
      soft: 'chapter-1/portraits/sir-raust/soft.webp',
      disappointed: 'chapter-1/portraits/sir-raust/disappointed.webp',
      calm: 'chapter-1/portraits/sir-raust/calm.webp',
      protective: 'chapter-1/portraits/sir-raust/protective.webp',
      battle_ready: 'chapter-1/portraits/sir-raust/battle_ready.webp',
    },
  },
  'servant-lyna': {
    id: 'servant-lyna',
    chapterId,
    displayName: 'Ліна',
    defaultEmotion: 'soft',
    defaultPortraitId: 'chapter-1/portraits/servant-lyna/soft.webp',
    defaultSide: 'left',
    portraitRefs: {
      soft: 'chapter-1/portraits/servant-lyna/soft.webp',
      nervous: 'chapter-1/portraits/servant-lyna/nervous.webp',
      embarrassed: 'chapter-1/portraits/servant-lyna/embarrassed.webp',
      serious: 'chapter-1/portraits/servant-lyna/serious.webp',
    },
  },
  'marna-voss': {
    id: 'marna-voss',
    chapterId,
    displayName: 'Марна Восс',
    defaultEmotion: 'professional',
    defaultPortraitId: 'chapter-1/portraits/marna-voss/professional.webp',
    defaultSide: 'left',
    portraitRefs: {
      professional: 'chapter-1/portraits/marna-voss/professional.webp',
      cold: 'chapter-1/portraits/marna-voss/cold.webp',
      sharp: 'chapter-1/portraits/marna-voss/sharp.webp',
      mocking: 'chapter-1/portraits/marna-voss/mocking.webp',
      superior: 'chapter-1/portraits/marna-voss/superior.webp',
    },
  },
  'orc-raider': {
    id: 'orc-raider',
    chapterId,
    displayName: 'Оркоїдний рейдер',
    defaultEmotion: 'dominant',
    defaultPortraitId: 'chapter-1/portraits/orc-raider/dominant.webp',
    defaultSide: 'right',
    portraitRefs: {
      dominant: 'chapter-1/portraits/orc-raider/dominant.webp',
    },
  },
  'old-prisoner': {
    id: 'old-prisoner',
    chapterId,
    displayName: 'Старий в’язень',
    defaultEmotion: 'neutral',
    defaultPortraitId: 'chapter-1/portraits/old-prisoner/neutral.webp',
    defaultSide: 'left',
    portraitRefs: {
      neutral: 'chapter-1/portraits/old-prisoner/neutral.webp',
      shifty: 'chapter-1/portraits/old-prisoner/shifty.webp',
      soft: 'chapter-1/portraits/old-prisoner/soft.webp',
      sad: 'chapter-1/portraits/old-prisoner/sad.webp',
    },
  },
  guard: {
    id: 'guard',
    chapterId,
    displayName: 'Охоронець',
    defaultEmotion: 'cold',
    defaultPortraitId: 'chapter-1/portraits/guard/cold.webp',
    defaultSide: 'right',
    portraitRefs: {
      cold: 'chapter-1/portraits/guard/cold.webp',
    },
  },
  'tessa-grey': {
    id: 'tessa-grey',
    chapterId,
    displayName: 'Тесса Грей',
    defaultEmotion: 'hard',
    defaultPortraitId: 'chapter-1/portraits/tessa-grey/hard.webp',
    defaultSide: 'left',
    portraitRefs: {
      hard: 'chapter-1/portraits/tessa-grey/hard.webp',
    },
  },
  'scarred-woman': {
    id: 'scarred-woman',
    chapterId,
    displayName: 'Шрамована жінка',
    defaultEmotion: 'hateful',
    defaultPortraitId: 'chapter-1/portraits/scarred-woman/hateful.webp',
    defaultSide: 'right',
    portraitRefs: {
      hateful: 'chapter-1/portraits/scarred-woman/hateful.webp',
    },
  },
  yarva: {
    id: 'yarva',
    chapterId,
    displayName: 'Ярва',
    defaultEmotion: 'cold',
    defaultPortraitId: 'chapter-1/portraits/yarva/cold.webp',
    defaultSide: 'right',
    portraitRefs: {
      cold: 'chapter-1/portraits/yarva/cold.webp',
      serious: 'chapter-1/portraits/yarva/serious.webp',
    },
  },
  grom: {
    id: 'grom',
    chapterId,
    displayName: 'Ґром',
    defaultEmotion: 'grim',
    defaultPortraitId: 'chapter-1/portraits/grom/grim.webp',
    defaultSide: 'right',
    portraitRefs: {
      grim: 'chapter-1/portraits/grom/grim.webp',
      neutral: 'chapter-1/portraits/grom/neutral.webp',
    },
  },
  rashek: {
    id: 'rashek',
    chapterId,
    displayName: 'Рашек',
    defaultEmotion: 'composed',
    defaultPortraitId: 'chapter-1/portraits/rashek/composed.webp',
    defaultSide: 'right',
    portraitRefs: {
      composed: 'chapter-1/portraits/rashek/composed.webp',
      stern: 'chapter-1/portraits/rashek/stern.webp',
    },
  },
  khazruk: {
    id: 'khazruk',
    chapterId,
    displayName: 'Хазрук',
    defaultEmotion: 'amused',
    defaultPortraitId: 'chapter-1/portraits/khazruk/amused.webp',
    defaultSide: 'right',
    portraitRefs: {
      amused: 'chapter-1/portraits/khazruk/amused.webp',
      smug: 'chapter-1/portraits/khazruk/smug.webp',
      composed: 'chapter-1/portraits/khazruk/composed.webp',
    },
  },
  orma: {
    id: 'orma',
    chapterId,
    displayName: 'Орма',
    defaultEmotion: 'serious',
    defaultPortraitId: 'chapter-1/portraits/orma/serious.webp',
    defaultSide: 'left',
    portraitRefs: {
      serious: 'chapter-1/portraits/orma/serious.webp',
      cold: 'chapter-1/portraits/orma/cold.webp',
    },
  },
  liena: {
    id: 'liena',
    chapterId,
    displayName: 'Лієна',
    defaultEmotion: 'fragile',
    defaultPortraitId: 'chapter-1/portraits/liena/fragile.webp',
    defaultSide: 'left',
    portraitRefs: {
      fragile: 'chapter-1/portraits/liena/fragile.webp',
      embarrassed: 'chapter-1/portraits/liena/embarrassed.webp',
      cold: 'chapter-1/portraits/liena/cold.webp',
    },
  },
  salver: {
    id: 'salver',
    chapterId,
    displayName: 'Салвер',
    defaultEmotion: 'tired',
    defaultPortraitId: 'chapter-1/portraits/salver/tired.webp',
    defaultSide: 'right',
    portraitRefs: {
      tired: 'chapter-1/portraits/salver/tired.webp',
      shifty: 'chapter-1/portraits/salver/shifty.webp',
    },
  },
  tris: {
    id: 'tris',
    chapterId,
    displayName: 'Тріс',
    defaultEmotion: 'cocky',
    defaultPortraitId: 'chapter-1/portraits/tris/cocky.webp',
    defaultSide: 'right',
    portraitRefs: {
      cocky: 'chapter-1/portraits/tris/cocky.webp',
      sharp: 'chapter-1/portraits/tris/sharp.webp',
      nervous: 'chapter-1/portraits/tris/nervous.webp',
    },
  },
  derun: {
    id: 'derun',
    chapterId,
    displayName: 'Дерун',
    defaultEmotion: 'shifty',
    defaultPortraitId: 'chapter-1/portraits/derun/shifty.webp',
    defaultSide: 'right',
    portraitRefs: {
      shifty: 'chapter-1/portraits/derun/shifty.webp',
      soft: 'chapter-1/portraits/derun/soft.webp',
    },
  },
  nadra: {
    id: 'nadra',
    chapterId,
    displayName: 'Надра',
    defaultEmotion: 'guarded',
    defaultPortraitId: 'chapter-1/portraits/nadra/guarded.webp',
    defaultSide: 'left',
    portraitRefs: {
      guarded: 'chapter-1/portraits/nadra/guarded.webp',
      serious: 'chapter-1/portraits/nadra/serious.webp',
      soft: 'chapter-1/portraits/nadra/soft.webp',
    },
  },
  krivozub: {
    id: 'krivozub',
    chapterId,
    displayName: 'Кривозуб',
    defaultEmotion: 'mocking',
    defaultPortraitId: 'chapter-1/portraits/krivozub/mocking.webp',
    defaultSide: 'right',
    portraitRefs: {
      mocking: 'chapter-1/portraits/krivozub/mocking.webp',
      amused: 'chapter-1/portraits/krivozub/amused.webp',
    },
  },
  sivra: {
    id: 'sivra',
    chapterId,
    displayName: 'Сівра',
    defaultEmotion: 'calm',
    defaultPortraitId: 'chapter-1/portraits/sivra/calm.webp',
    defaultSide: 'left',
    portraitRefs: {
      calm: 'chapter-1/portraits/sivra/calm.webp',
      careful: 'chapter-1/portraits/sivra/careful.webp',
    },
  },
  'ner-azet': {
    id: 'ner-azet',
    chapterId,
    displayName: 'Нер-Азет',
    defaultEmotion: 'whisper',
    defaultPortraitId: 'chapter-1/portraits/ner-azet/whisper.webp',
    defaultSide: 'left',
    portraitRefs: {
      whisper: 'chapter-1/portraits/ner-azet/whisper.webp',
      hunger: 'chapter-1/portraits/ner-azet/hunger.webp',
      invasion: 'chapter-1/portraits/ner-azet/invasion.webp',
    },
  },
};
