import type { SceneGenerationDocument } from '@engine/types/sceneGeneration';

import { chapter1ThornDepartureCorsetTieReplayScene } from './replays/corset-tie.replay.scene-generation';
import { chapter1ThornDepartureFatherBetrayalReplayScene } from './replays/father-betrayal.replay.scene-generation';

export const chapter1ThornDepartureSceneGenerationDocument = {
  id: 'chapter-1/scene-generation/thorn-departure',
  schemaVersion: 1,
  title: 'Morning In The Thorn House',
  meta: {
    chapterId: 'chapter-1',
    language: 'uk',
    defaultBackgroundId: 'prologue/backgrounds/thorn_estate_mirella_room_morning',
    defaultMusicId: 'prologue/music/house_of_form',
    defaultStage: {
      characters: [
        {
          speakerId: 'mirella',
          emotion: 'guarded',
          portraitId: 'prologue/portraits/mirella/guarded.webp',
          outfitId: 'dress-pristine',
          placement: { x: 20, scale: 1.02 },
        },
      ],
      focusCharacterId: 'mirella',
    },
  },
  scenes: {
    'chapter-1/scene/thorn-estate/morning': {
      id: 'chapter-1/scene/thorn-estate/morning',
      mode: 'sequence',
      title: 'Morning In The Thorn House',
      description: 'The house wakes before the people inside it do.',
      startNodeId: 'thorn-morning-1',
      backgroundId: 'prologue/backgrounds/thorn_estate_mirella_room_morning',
      music: {
        action: 'play',
        musicId: 'prologue/music/house_of_form',
        fadeMs: 900,
        loop: true,
      },
      nodes: {
        'thorn-morning-1': {
          id: 'thorn-morning-1',
          type: 'narration',
          text: 'Ранок у домі Торнів починався не зі світла. Світло приходило пізніше, на вже відсунуті штори, на воду в срібній мисці, на стрічки, розкладені в правильному порядку, на дім, який збирав себе у форму ще до того, як прокидалися люди.',
          onEnterEffects: [
            { type: 'setCharacterOutfit', characterId: 'mirella', outfitId: 'dress-pristine' },
            { type: 'setFlag', flagId: 'chapter1.thorn.morning.entered', value: true },
          ],
          nextNodeId: 'thorn-morning-2',
        },
        'thorn-morning-2': {
          id: 'thorn-morning-2',
          type: 'dialogue',
          speakerId: 'tanya',
          emotion: 'careful',
          text: 'Пані. Леді Сера просила не спізнюватися.',
          nextNodeId: 'thorn-morning-3',
        },
        'thorn-morning-3': {
          id: 'thorn-morning-3',
          type: 'narration',
          text: 'Таня рухалась, як завжди, тихо й майже безтілесно, ніби намагалась не лишити по собі ані звуку, ані сліду, ані приводу згадати, що вона була тут. На мить Міреллі здалося, що найнебезпечніші люди в цьому домі не ті, кого бояться, а ті, хто навчився ставати майже невидимими.',
          nextNodeId: 'thorn-morning-4',
        },
        'thorn-morning-4': {
          id: 'thorn-morning-4',
          type: 'narration',
          text: 'Корсет ліг на талію холодно. Таня затягнула шнурівку, зупинилась пальцями на стрічках і тихо спитала, чи не надто туго.',
          onEnterEffects: [
            {
              type: 'unlockSceneReplay',
              sceneId: 'chapter-1/scene/thorn-estate/replay/corset-tie',
            },
          ],
          nextNodeId: 'thorn-morning-5',
        },
        'thorn-morning-5': {
          id: 'thorn-morning-5',
          type: 'choice',
          speakerId: 'mirella',
          emotion: 'guarded',
          text: 'Мірелла дивиться на себе в дзеркало й вирішує, що сьогодні важливіше: бездоганна форма, дихання чи сама звичка не просити зайвого.',
          choices: [
            {
              id: 'thorn-morning-5-tighten',
              text: '«Затягни сильніше. Я маю виглядати бездоганно».',
              effects: [
                { type: 'changeStat', key: 'domination', delta: 1 },
                { type: 'changeMeta', key: 'reputation', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.corset.tightened', value: true },
              ],
              nextNodeId: 'thorn-morning-6-tighten',
            },
            {
              id: 'thorn-morning-5-loosen',
              text: '«Послаб трохи. Я маю доїхати, а не задихнутися».',
              effects: [
                { type: 'changeStat', key: 'pragmatism', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.corset.loosened', value: true },
              ],
              nextNodeId: 'thorn-morning-6-loosen',
            },
            {
              id: 'thorn-morning-5-silence',
              text: 'Змовчати й дозволити їй самій вирішити, як туго затягнути шнурівку.',
              effects: [
                { type: 'changeStat', key: 'submission', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.corset.silent', value: true },
              ],
              nextNodeId: 'thorn-morning-6-silence',
            },
          ],
        },
        'thorn-morning-6-tighten': {
          id: 'thorn-morning-6-tighten',
          type: 'narration',
          text: 'Таня слухняно затягнула ще на півдюйма. Повітря стало дорожчим, зате постава майже бездоганною. Після цього вона дивилась на Міреллу трохи обережніше, ніби вперше побачила, на що та готова заради форми.',
          nextNodeId: 'thorn-morning-7',
        },
        'thorn-morning-6-loosen': {
          id: 'thorn-morning-6-loosen',
          type: 'narration',
          text: 'Таня одразу послабила шнурівку. Полегшення було не великим, але достатнім, щоб нагадати: іноді виживання починається з відмови від красивого зайвого страждання.',
          nextNodeId: 'thorn-morning-7',
        },
        'thorn-morning-6-silence': {
          id: 'thorn-morning-6-silence',
          type: 'narration',
          text: 'Мірелла нічого не сказала, і Таня сама трохи послабила стрічки. Це була така дрібна послуга, яка в добрих домах нічого б не означала, а тут відразу ставала формою небезпечної близькості.',
          nextNodeId: 'thorn-morning-7',
        },
        'thorn-morning-7': {
          id: 'thorn-morning-7',
          type: 'narration',
          text: 'У коридорі Мірелла застала Арена з Танею. Він не торкався її, але вже стояв надто близько, на тій відстані, де чужий страх починає працювати без рук.',
          nextNodeId: 'thorn-morning-8',
        },
        'thorn-morning-8': {
          id: 'thorn-morning-8',
          type: 'dialogue',
          speakerId: 'aren',
          emotion: 'amused',
          text: 'Ви всі так стараєтесь триматися рівно. Прислуга, міські святенники, гугони у своїх норах... А всередині всі однаково бідні. Просто одним дають ліврею, а іншим лахміття.',
          nextNodeId: 'thorn-morning-9',
        },
        'thorn-morning-9': {
          id: 'thorn-morning-9',
          type: 'narration',
          text: 'Таня мовчала. Пальці на срібному краї таці тремтіли ледь-ледь, так, що це побачила б тільки людина, яка сама знає, що таке страх, стиснутий до розміру жесту.',
          nextNodeId: 'thorn-morning-10',
        },
        'thorn-morning-10': {
          id: 'thorn-morning-10',
          type: 'choice',
          speakerId: 'mirella',
          emotion: 'cold',
          text: 'Мірелла втручається рівно настільки, наскільки готова показати себе перед Ареном і Танею одночасно.',
          choices: [
            {
              id: 'thorn-morning-10-cut-him',
              text: 'Холодно перебити Арена й повернути сцені пристойний вигляд.',
              effects: [
                { type: 'changeStat', key: 'domination', delta: 1 },
                { type: 'changeMeta', key: 'reputation', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.arenInterrupted', value: true },
              ],
              nextNodeId: 'thorn-morning-11-cut-him',
            },
            {
              id: 'thorn-morning-10-help-her',
              text: 'Звернутись до Тані так, ніби саме вона тут головна людина в розмові.',
              effects: [
                { type: 'changeStat', key: 'altruism', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.tanyaShielded', value: true },
              ],
              nextNodeId: 'thorn-morning-11-help-her',
            },
            {
              id: 'thorn-morning-10-mark-it',
              text: 'Нічого не загострювати. Просто запам’ятати, як саме він це робить.',
              effects: [
                { type: 'changeStat', key: 'machiavellianism', delta: 1 },
                { type: 'changeStat', key: 'paranoia', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.arenTechniqueObserved', value: true },
              ],
              nextNodeId: 'thorn-morning-11-mark-it',
            },
          ],
        },
        'thorn-morning-11-cut-him': {
          id: 'thorn-morning-11-cut-him',
          type: 'dialogue',
          speakerId: 'mirella',
          emotion: 'cold',
          text: 'Кузене, якщо ти хочеш поговорити про бідність, спробуй спершу не виглядати людиною, якій ніколи не доводилося лишатися без захисту.',
          nextNodeId: 'thorn-morning-12',
        },
        'thorn-morning-11-help-her': {
          id: 'thorn-morning-11-help-her',
          type: 'dialogue',
          speakerId: 'mirella',
          emotion: 'calm',
          text: 'Таню, матір уже чекають у їдальні. Не затримуйся через чужу філософію.',
          nextNodeId: 'thorn-morning-12',
        },
        'thorn-morning-11-mark-it': {
          id: 'thorn-morning-11-mark-it',
          type: 'narration',
          text: 'Мірелла не стала різати сцену вголос. Вона тільки вийшла в коридор так, щоб Арен побачив: його почули, його запам’ятали, і одного разу це може повернутися до нього в іншій формі.',
          nextNodeId: 'thorn-morning-12',
        },
        'thorn-morning-12': {
          id: 'thorn-morning-12',
          type: 'narration',
          text: 'Таня зникла так швидко, ніби розмова могла прилипнути до її шкіри. Арен рушив до їдальні поруч із Міреллою легко, безпечно, майже весело. Саме це і було в ньому найгидкішим.',
          nextSceneId: 'chapter-1/scene/thorn-estate/breakfast',
        },
      },
    },

    'chapter-1/scene/thorn-estate/breakfast': {
      id: 'chapter-1/scene/thorn-estate/breakfast',
      mode: 'sequence',
      title: 'Breakfast',
      description: 'A family table that behaves like a council chamber.',
      startNodeId: 'thorn-breakfast-1',
      backgroundId: 'prologue/backgrounds/thorn_estate_dining_hall_morning',
      nodes: {
        'thorn-breakfast-1': {
          id: 'thorn-breakfast-1',
          type: 'narration',
          text: 'За столом уже зібралися всі. Перед Гаєм лежали листи, охоронні донесення, рахунки, маршрути й короткі нотатки для ради. Сера сиділа бездоганно зібрана, із тонким золотим пилом на вилицях, знаком віри, яка вчила не відмовлятися від форми, а освячувати її. Едран був занадто прямий для цього дому, Арен занадто звичний до його гнилі, щоб вона хоч колись його бентежила.',
          nextNodeId: 'thorn-breakfast-2',
        },
        'thorn-breakfast-2': {
          id: 'thorn-breakfast-2',
          type: 'dialogue',
          speakerId: 'lord-guy',
          emotion: 'cold',
          text: 'Уночі на північному маршруті зняли двох людей із листівками повстанців. До вечора говоритимуть не про листівки. Говоритимуть про слабкість нашого дому.',
          nextNodeId: 'thorn-breakfast-3',
        },
        'thorn-breakfast-3': {
          id: 'thorn-breakfast-3',
          type: 'dialogue',
          speakerId: 'lady-sera',
          emotion: 'composed',
          text: 'Люди завжди охочіше вірять у тріщину, ніж у камінь. Тому камінь має виглядати так, ніби він не знає втоми.',
          nextNodeId: 'thorn-breakfast-4',
        },
        'thorn-breakfast-4': {
          id: 'thorn-breakfast-4',
          type: 'dialogue',
          speakerId: 'edran',
          emotion: 'stern',
          text: 'Проблема не в листівках. Проблема в тому, що гугони знову рухаються старими проходами, а місту цікавіше, хто з ким сяде на балу.',
          nextNodeId: 'thorn-breakfast-5',
        },
        'thorn-breakfast-5': {
          id: 'thorn-breakfast-5',
          type: 'dialogue',
          speakerId: 'aren',
          emotion: 'amused',
          text: 'Місто любить красиві страхи. Вони пахнуть краще за шахтний пил.',
          nextNodeId: 'thorn-breakfast-6',
        },
        'thorn-breakfast-6': {
          id: 'thorn-breakfast-6',
          type: 'choice',
          speakerId: 'mirella',
          emotion: 'guarded',
          text: 'За цим столом давно вже не сперечалися про правду. Тут вирішували, чия версія реальності сьогодні коштуватиме дорожче.',
          choices: [
            {
              id: 'thorn-breakfast-6-support-guy',
              text: '«Слабкість дому першими купують не повстанці, а сусіди».',
              effects: [
                { type: 'changeStat', key: 'machiavellianism', delta: 1 },
                { type: 'changeMeta', key: 'reputation', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.breakfast.supportedGuy', value: true },
                {
                  type: 'setFlag',
                  flagId: 'chapter1.thorn.breakfast.familyTensionRaised',
                  value: true,
                },
              ],
              nextNodeId: 'thorn-breakfast-7-support-guy',
            },
            {
              id: 'thorn-breakfast-6-question-sera',
              text: '«Мамо, ви говорите про форму так, ніби вона важливіша за саму людину».',
              effects: [
                { type: 'changeStat', key: 'honor', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.breakfast.questionedSera', value: true },
              ],
              nextNodeId: 'thorn-breakfast-7-question-sera',
            },
            {
              id: 'thorn-breakfast-6-support-edran',
              text: '«Якщо гугони вже рухаються, то чому ми говоримо про чутки, а не про проходи?»',
              effects: [
                { type: 'changeStat', key: 'honor', delta: 1 },
                { type: 'changeStat', key: 'pragmatism', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.breakfast.supportedEdran', value: true },
              ],
              nextNodeId: 'thorn-breakfast-7-support-edran',
            },
            {
              id: 'thorn-breakfast-6-cut-aren',
              text: '«Чужою бідністю найзручніше жартують ті, кому ніколи не доводилося бути без захисту».',
              effects: [
                { type: 'changeStat', key: 'domination', delta: 1 },
                { type: 'changeMeta', key: 'badReputation', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.breakfast.cutAren', value: true },
                {
                  type: 'setFlag',
                  flagId: 'chapter1.thorn.breakfast.familyTensionRaised',
                  value: true,
                },
              ],
              nextNodeId: 'thorn-breakfast-7-cut-aren',
            },
          ],
        },
        'thorn-breakfast-7-support-guy': {
          id: 'thorn-breakfast-7-support-guy',
          type: 'narration',
          text: 'Гай коротко кивнув, ніби поставив підпис під уже очікуваною відповіддю. Це не було схваленням у теплому сенсі. Але в цьому домі й така суха реєстрація ваги вже вважалась формою близькості.',
          nextNodeId: 'thorn-breakfast-8',
        },
        'thorn-breakfast-7-question-sera': {
          id: 'thorn-breakfast-7-question-sera',
          type: 'dialogue',
          speakerId: 'lady-sera',
          emotion: 'composed',
          text: 'Форма не важливіша за людину. Вона просто перша річ, яку в людини відбирає хаос. І перша, яку доводиться збирати назад.',
          nextNodeId: 'thorn-breakfast-8',
        },
        'thorn-breakfast-7-support-edran': {
          id: 'thorn-breakfast-7-support-edran',
          type: 'narration',
          text: 'Едран глянув на Міреллу без усмішки, але уважніше, ніж раніше. Так дивляться на людину, яку раптом починають сприймати не як прикрасу виїзду, а як співрозмовницю.',
          nextNodeId: 'thorn-breakfast-8',
        },
        'thorn-breakfast-7-cut-aren': {
          id: 'thorn-breakfast-7-cut-aren',
          type: 'narration',
          text: 'Арен посміхнувся майже щиро. Саме такі миті він любив: коли образу можна прийняти як гру, а пізніше повернути вже без свідків.',
          nextNodeId: 'thorn-breakfast-8',
        },
        'thorn-breakfast-8': {
          id: 'thorn-breakfast-8',
          type: 'narration',
          text: 'Після цього ніхто не повертався до сказаного прямо. Але кожна репліка лишилась за столом, як прибор, який ще доведеться взяти до рук.',
          nextSceneId: 'chapter-1/scene/thorn-estate/departure-flight',
        },
      },
    },

    'chapter-1/scene/thorn-estate/departure-flight': {
      id: 'chapter-1/scene/thorn-estate/departure-flight',
      mode: 'sequence',
      title: 'Departure And Flight',
      description: 'The house turns into a machine and carries them toward the mountain sector.',
      startNodeId: 'thorn-flight-1',
      backgroundId: 'prologue/backgrounds/thorn_estate_east_platform_day',
      nodes: {
        'thorn-flight-1': {
          id: 'thorn-flight-1',
          type: 'narration',
          text: 'Східна платформа була останнім місцем, де Торни ще нагадували дім, а не механізм. Гай перевіряв супровід, Сера поправила Міреллі рукавичку з тією сухою уважністю, яку не можна було сплутати з ніжністю, але й байдужістю вона не була. Арен позіхнув на вітер. Едран уже дивився не на людей, а на хребет і темні транспортні лінії під ним.',
          nextNodeId: 'thorn-flight-2',
        },
        'thorn-flight-2': {
          id: 'thorn-flight-2',
          type: 'narration',
          text: 'У польоті місто розгорталося шарами: спершу ще красиве, далі робоче, далі виснажене, а за ним ішли гори, надто порізані, щоб лишатися просто краєвидом.',
          nextNodeId: 'thorn-flight-3',
        },
        'thorn-flight-3': {
          id: 'thorn-flight-3',
          type: 'choice',
          speakerId: 'mirella',
          emotion: 'thinking',
          text: 'Коротке перемир’я польоту дає Міреллі рідкісний шанс вибрати, до кого саме вона зараз простягне думку: до матері, до дядька чи тільки до власного спостереження.',
          choices: [
            {
              id: 'thorn-flight-3-ask-sera',
              text: 'Піти до матері й спитати, що саме її віра рятує в таких домах.',
              effects: [
                { type: 'changeStat', key: 'restraint', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.flight.talkedToSera', value: true },
              ],
              nextNodeId: 'thorn-flight-4-ask-sera',
            },
            {
              id: 'thorn-flight-3-ask-edran',
              text: 'Піти до Едрана й спитати, чому він сприймає гугонів серйозніше за інших.',
              effects: [
                { type: 'changeStat', key: 'pragmatism', delta: 1 },
                { type: 'changeStat', key: 'honor', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.flight.talkedToEdran', value: true },
              ],
              nextNodeId: 'thorn-flight-4-ask-edran',
            },
            {
              id: 'thorn-flight-3-watch-all',
              text: 'Не втручатися в розмови. Просто дивитися, як кожен із них тримає свою роль.',
              effects: [
                { type: 'changeStat', key: 'machiavellianism', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.flight.observedFamily', value: true },
              ],
              nextNodeId: 'thorn-flight-4-watch-all',
            },
          ],
        },
        'thorn-flight-4-ask-sera': {
          id: 'thorn-flight-4-ask-sera',
          type: 'dialogue',
          speakerId: 'lady-sera',
          emotion: 'calm',
          text: 'Моя віра не робить світ чистим, Мірелло. Вона лише не дає мені розсипатися швидше за нього. У деякі дні цього вже достатньо.',
          nextNodeId: 'thorn-flight-5',
        },
        'thorn-flight-4-ask-edran': {
          id: 'thorn-flight-4-ask-edran',
          type: 'dialogue',
          speakerId: 'edran',
          emotion: 'stern',
          text: 'Бо ті, кого всі звикли зневажати, часто першими помічають, де починає валитися камінь. А зверху це називають чутками, поки когось не завалить насправді.',
          nextNodeId: 'thorn-flight-5',
        },
        'thorn-flight-4-watch-all': {
          id: 'thorn-flight-4-watch-all',
          type: 'narration',
          text: 'Мірелла не підійшла ні до кого. Вона дивилася, як батько випрямляє спину щоразу, коли хоче зігнути кімнату під себе, як мати ховає втому в точності рухів, як Едран дратується надто чесно, а Арен нудьгує так, ніби нудьга давно стала його улюбленою формою жорстокості.',
          nextNodeId: 'thorn-flight-5',
        },
        'thorn-flight-5': {
          id: 'thorn-flight-5',
          type: 'narration',
          text: 'До моменту, коли повітряний човен почав знижуватися над уступами, Мірелла вже знала: жоден із дорослих поруч не був пласким. І саме тому вони були страшніші, ніж якби зводилися до однієї риси.',
          nextSceneId: 'chapter-1/scene/thorn-estate/mountain-sector',
        },
      },
    },

    'chapter-1/scene/thorn-estate/mountain-sector': {
      id: 'chapter-1/scene/thorn-estate/mountain-sector',
      mode: 'sequence',
      title: 'Mountain Sector',
      description: 'The industrial heart of the family strips beauty down to function.',
      startNodeId: 'thorn-mountain-1',
      backgroundId: 'prologue/backgrounds/thorn_mines_third_ledge_overlook',
      nodes: {
        'thorn-mountain-1': {
          id: 'thorn-mountain-1',
          type: 'narration',
          text: 'Гірський комплекс Торнів не просив любові. Він просив звички. Платформа врізалася в уступ, нижче тягнулися переходи, шахтні колодязі, склади, опори, транспортні лінії й темні отвори в породі. Щойно Гай ступив на метал, він змінився: у домі він був центром порядку, а тут сам був порядком.',
          nextNodeId: 'thorn-mountain-2',
        },
        'thorn-mountain-2': {
          id: 'thorn-mountain-2',
          type: 'narration',
          text: 'Поки батько слухав звіти, Мірелла встигла побачити більше, ніж їй, певно, планували показати: руки, з яких пил уже не виводився до кінця, хлопця з кашлем, жінку на перевалочному вузлі, що сперечалась із писарем так тихо, ніби від цієї стриманості залежав не просто запис, а чийсь обід.',
          nextNodeId: 'thorn-mountain-3',
        },
        'thorn-mountain-3': {
          id: 'thorn-mountain-3',
          type: 'choice',
          speakerId: 'mirella',
          emotion: 'guarded',
          text: 'У секторі все ніби саме пропонує визначитися: дивитися на людей, на цифри чи на батькову логіку як на щось, що теж можна вивчити.',
          choices: [
            {
              id: 'thorn-mountain-3-workers',
              text: 'Придивитися до людей унизу й до того, як вони тримаються одне за одного.',
              effects: [
                { type: 'changeStat', key: 'altruism', delta: 1 },
                { type: 'changeMeta', key: 'reputation', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.mountain.sawWorkers', value: true },
              ],
              nextNodeId: 'thorn-mountain-4-workers',
            },
            {
              id: 'thorn-mountain-3-ledgers',
              text: 'Придивитися до записів, опор і технічних дрібниць, які видають правду точніше за голоси.',
              effects: [
                { type: 'changeStat', key: 'pragmatism', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.mountain.readSector', value: true },
              ],
              nextNodeId: 'thorn-mountain-4-ledgers',
            },
            {
              id: 'thorn-mountain-3-father',
              text: 'Придивитися до батька і до того, як саме він утримує все це разом.',
              effects: [
                { type: 'changeStat', key: 'domination', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.mountain.readGuy', value: true },
              ],
              nextNodeId: 'thorn-mountain-4-father',
            },
          ],
        },
        'thorn-mountain-4-workers': {
          id: 'thorn-mountain-4-workers',
          type: 'narration',
          text: 'Внизу люди не виглядали шляхетно, героїчно чи навіть особливо нещасно. Вони просто вміли тримати день разом, поки камінь не вирішив інакше. Саме ця звичайність раптом зробила їх реальнішими за всі ранкові розмови про честь і форму.',
          nextNodeId: 'thorn-mountain-5',
        },
        'thorn-mountain-4-ledgers': {
          id: 'thorn-mountain-4-ledgers',
          type: 'narration',
          text: 'На секторі брехня виглядала не як гучна фраза, а як дрібний перекіс у цифрах, як надто впевнене «все під контролем», як опора, що стоїть іще день лише тому, що нікому не хочеться зупиняти зміну.',
          nextNodeId: 'thorn-mountain-5',
        },
        'thorn-mountain-4-father': {
          id: 'thorn-mountain-4-father',
          type: 'narration',
          text: 'Гай говорив коротко, і кожне слово одразу вбудовувалося в чужі рухи. Він не здавався садистом чи чудовиськом. Він здавався людиною, яка надто давно звикла плутати керування з єдиною можливою формою відповідальності.',
          nextNodeId: 'thorn-mountain-5',
        },
        'thorn-mountain-5': {
          id: 'thorn-mountain-5',
          type: 'narration',
          text: 'Саме тут Мірелла вперше роздивилася Галена зблизька. Сивий від пилу, з рукою, яку колись погано зібрали після перелому, він стояв без жодної позірної гідності і саме тому його слухали уважніше, ніж багатьох охайних людей нагорі.',
          nextSceneId: 'chapter-1/scene/thorn-estate/galen',
        },
      },
    },

    'chapter-1/scene/thorn-estate/galen': {
      id: 'chapter-1/scene/thorn-estate/galen',
      mode: 'sequence',
      title: 'Galen',
      description: 'A practical act of mercy becomes a public breach of discipline.',
      startNodeId: 'thorn-galen-1',
      backgroundId: 'prologue/backgrounds/thorn_mines_third_ledge_overlook',
      nodes: {
        'thorn-galen-1': {
          id: 'thorn-galen-1',
          type: 'narration',
          text: 'Оглядовий майданчик висів над третім уступом, і шахта читалася звідти як розкритий орган: металеві переходи, лампи в сітках, чорні вени породи, люди, які внизу вже майже зливалися з механізмом.',
          nextNodeId: 'thorn-galen-2',
        },
        'thorn-galen-2': {
          id: 'thorn-galen-2',
          type: 'dialogue',
          speakerId: 'galen',
          emotion: 'serious',
          text: 'Я зупинив нижній ряд. У породі вже пішов звук. Ще трохи, і людей би засипало.',
          nextNodeId: 'thorn-galen-3',
        },
        'thorn-galen-3': {
          id: 'thorn-galen-3',
          type: 'dialogue',
          speakerId: 'lord-guy',
          emotion: 'cold',
          text: 'Тобто ти скасував наказ, бо вирішив, що твоє відчуття каменю важливіше за порядок сектора.',
          nextNodeId: 'thorn-galen-4',
        },
        'thorn-galen-4': {
          id: 'thorn-galen-4',
          type: 'dialogue',
          speakerId: 'galen',
          emotion: 'serious',
          text: 'Я не дав людям померти. Якщо вам потрібне інше формулювання, я його не маю.',
          nextNodeId: 'thorn-galen-5',
        },
        'thorn-galen-5': {
          id: 'thorn-galen-5',
          type: 'narration',
          text: 'Наказ покарати його прозвучав тихо. Саме тому всі почули його відразу. Охоронець збив Галена на одне коліно ударом держака під ребра, і метал відгукнувся чистіше, ніж людський звук.',
          nextNodeId: 'thorn-galen-6',
        },
        'thorn-galen-6': {
          id: 'thorn-galen-6',
          type: 'choice',
          speakerId: 'mirella',
          emotion: 'shaken',
          text: 'Найгіршим було не саме покарання, а те, як швидко простір навколо погодився з ним. Тіло вимагало від Мірелли визначитися, ким бути в цю мить.',
          choices: [
            {
              id: 'thorn-galen-6-watch',
              text: 'Дивитися до кінця, не дозволяючи собі відвести очі.',
              effects: [
                { type: 'changeStat', key: 'domination', delta: 1 },
                { type: 'changeStat', key: 'pragmatism', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.galen.watched', value: true },
              ],
              nextNodeId: 'thorn-galen-7-watch',
            },
            {
              id: 'thorn-galen-6-turn-away',
              text: 'Відвернутися. Є речі, які ще не можна впускати в себе до кінця.',
              effects: [
                { type: 'changeStat', key: 'restraint', delta: 1 },
                { type: 'changeStat', key: 'paranoia', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.galen.turnedAway', value: true },
              ],
              nextNodeId: 'thorn-galen-7-turn-away',
            },
            {
              id: 'thorn-galen-6-remember',
              text: 'Запам’ятати все мовчки, без жодного руху назовні.',
              effects: [
                { type: 'changeStat', key: 'machiavellianism', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.galen.remembered', value: true },
              ],
              nextNodeId: 'thorn-galen-7-remember',
            },
          ],
        },
        'thorn-galen-7-watch': {
          id: 'thorn-galen-7-watch',
          type: 'narration',
          text: 'Мірелла дивилася не на батька, а на те, як Гален не дозволив зробити з болю виставу. Від цього ставало не легше, тільки зрозуміліше, скільки сил у людині може забрати сама відмова благати.',
          nextNodeId: 'thorn-galen-8',
        },
        'thorn-galen-7-turn-away': {
          id: 'thorn-galen-7-turn-away',
          type: 'narration',
          text: 'Вона відвела очі надто пізно: звук уже встиг зайти всередину й там лишитися. Відвернутися виявилося не втечею, а тільки іншим способом пам’ятати.',
          nextNodeId: 'thorn-galen-8',
        },
        'thorn-galen-7-remember': {
          id: 'thorn-galen-7-remember',
          type: 'narration',
          text: 'Вона запам’ятовувала не самого Галена, а порядок рухів: хто відступив, хто не здригнувся, хто дивився на батька перед тим, як опустити очі. Саме так, мабуть, і збирають знання, потрібне для виживання в сильних домах.',
          nextNodeId: 'thorn-galen-8',
        },
        'thorn-galen-8': {
          id: 'thorn-galen-8',
          type: 'narration',
          text: 'Міреллу нудило. І майже так само нудило від іншого: якась частина її все ж розуміла логіку батька. Не приймала. Не пробачала. Але розуміла.',
          nextSceneId: 'chapter-1/scene/thorn-estate/service-corridor',
        },
      },
    },

    'chapter-1/scene/thorn-estate/service-corridor': {
      id: 'chapter-1/scene/thorn-estate/service-corridor',
      mode: 'sequence',
      title: 'Service Corridor',
      description: 'Power reveals that it does not change shape when it enters intimacy.',
      startNodeId: 'thorn-corridor-1',
      backgroundId: 'prologue/backgrounds/thorn_mines_private_corridor_dim',
      nodes: {
        'thorn-corridor-1': {
          id: 'thorn-corridor-1',
          type: 'narration',
          text: 'Після огляду Мірелла звернула не туди, куди вели гостей. У службовому коридорі лампи горіли нижче, а метал уже не шумів відкрито, лише пам’ятав про шахту в самих стінах.',
          nextNodeId: 'thorn-corridor-2',
        },
        'thorn-corridor-2': {
          id: 'thorn-corridor-2',
          type: 'narration',
          text: 'Вона почула жіночий сміх, не вільний, а той обережний сміх, яким люди іноді платять старшим за коротке полегшення. Далі був батько, жінка зі сортувального відділу і жест, у якому вдячність уже змішалася з підпорядкуванням.',
          onEnterEffects: [
            {
              type: 'unlockSceneReplay',
              sceneId: 'chapter-1/scene/thorn-estate/replay/father-betrayal',
            },
            { type: 'setFlag', flagId: 'chapter1.thorn.fatherBetrayalSeen', value: true },
          ],
          nextNodeId: 'thorn-corridor-3',
        },
        'thorn-corridor-3': {
          id: 'thorn-corridor-3',
          type: 'choice',
          speakerId: 'mirella',
          emotion: 'hurt',
          text: 'Найгіршим було не те, що він зраджував матір. Найгіршим було, що навіть тут він лишався тією самою системою: ласка як монета, близькість як ще одна форма влади.',
          choices: [
            {
              id: 'thorn-corridor-3-leave',
              text: 'Відійти відразу, не даючи цій сцені торкнутися тебе більше, ніж вона вже торкнулась.',
              effects: [
                { type: 'changeStat', key: 'restraint', delta: 1 },
                { type: 'changeStat', key: 'paranoia', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.fatherBetrayal.leftEarly', value: true },
              ],
              nextNodeId: 'thorn-corridor-4-leave',
            },
            {
              id: 'thorn-corridor-3-study',
              text: 'Затриматися на одну мить довше й зрозуміти, як саме тут працює милість.',
              effects: [
                { type: 'changeStat', key: 'machiavellianism', delta: 1 },
                { type: 'changeStat', key: 'pragmatism', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.fatherBetrayal.studied', value: true },
              ],
              nextNodeId: 'thorn-corridor-4-study',
            },
            {
              id: 'thorn-corridor-3-moral-recoil',
              text: 'Відчути огиду не тільки до зради, а й до самого механізму, який робить таке буденним.',
              effects: [
                { type: 'changeStat', key: 'honor', delta: 1 },
                { type: 'changeStat', key: 'altruism', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.fatherBetrayal.recoiled', value: true },
              ],
              nextNodeId: 'thorn-corridor-4-moral-recoil',
            },
          ],
        },
        'thorn-corridor-4-leave': {
          id: 'thorn-corridor-4-leave',
          type: 'narration',
          text: 'Мірелла відступила раніше, ніж її могли помітити. Хотілося тільки одного: вмитися чимось дуже холодним і зробити вигляд, що шкіра ще належить їй самій.',
          nextNodeId: 'thorn-corridor-5',
        },
        'thorn-corridor-4-study': {
          id: 'thorn-corridor-4-study',
          type: 'narration',
          text: 'Вона затрималась на мить довше, ніж варто було. Цього вистачило, щоб зрозуміти головне: дім батька не закінчується на його наказах. Він простягається далі, у те, як він винагороджує, прив’язує, заспокоює й купує мовчання.',
          nextNodeId: 'thorn-corridor-5',
        },
        'thorn-corridor-4-moral-recoil': {
          id: 'thorn-corridor-4-moral-recoil',
          type: 'narration',
          text: 'Шок був коротким. Огида виявилася довшою. Не до тіла, не до бажання, а до того, як легко в сильних людей навіть полегшення для інших стає частиною управління.',
          nextNodeId: 'thorn-corridor-5',
        },
        'thorn-corridor-5': {
          id: 'thorn-corridor-5',
          type: 'narration',
          text: 'Коли вони повернулися додому, лакей прийняв рукавички у Мірелли так, ніби день минув звичайно. Саме ця бездоганна нормальність після шахти й коридору зробила дім майже нестерпним.',
          nextSceneId: 'chapter-1/scene/thorn-estate/orangery',
        },
      },
    },

    'chapter-1/scene/thorn-estate/orangery': {
      id: 'chapter-1/scene/thorn-estate/orangery',
      mode: 'sequence',
      title: 'Orangery',
      description: 'The mother refuses to lie, but refuses simplicity too.',
      startNodeId: 'thorn-orangery-1',
      backgroundId: 'prologue/backgrounds/thorn_estate_orangery_evening',
      nodes: {
        'thorn-orangery-1': {
          id: 'thorn-orangery-1',
          type: 'narration',
          text: 'Оранжерея була єдиним місцем у домі, де життя не виглядало повністю приборканим. Під склом трималося тепле повітря, важкий запах землі й листя, занадто розкішного, щоб бути невинним. Сера стояла біля кам’яної полиці й обрізала сухий край листка маленьким ножем.',
          nextNodeId: 'thorn-orangery-2',
        },
        'thorn-orangery-2': {
          id: 'thorn-orangery-2',
          type: 'dialogue',
          speakerId: 'mirella',
          emotion: 'hurt',
          text: 'Ти знала.',
          nextNodeId: 'thorn-orangery-3',
        },
        'thorn-orangery-3': {
          id: 'thorn-orangery-3',
          type: 'dialogue',
          speakerId: 'lady-sera',
          emotion: 'tired',
          text: 'Я знала достатньо. У певному віці жінка перестає плутати незнання з чеснотою.',
          nextNodeId: 'thorn-orangery-4',
        },
        'thorn-orangery-4': {
          id: 'thorn-orangery-4',
          type: 'dialogue',
          speakerId: 'lady-sera',
          emotion: 'calm',
          text: 'Моя віра не про те, щоб світ був чистим. Вона про те, щоб не віддати себе хаосу швидше, ніж ти встигнеш зібрати власну форму. Я не молюся про справедливість щодня. Я молюся, щоб не розсипатися раніше за неї.',
          nextNodeId: 'thorn-orangery-5',
        },
        'thorn-orangery-5': {
          id: 'thorn-orangery-5',
          type: 'choice',
          speakerId: 'mirella',
          emotion: 'shaken',
          text: 'Мірелла бачить перед собою не святу й не зрадницю, а дорослу жінку, яка давно живе між наслідками. Від цього не легше. Зате важче брехати собі.',
          choices: [
            {
              id: 'thorn-orangery-5-call-submission',
              text: '«Це не витривалість. Це покора».',
              conditions: [{ type: 'statGte', key: 'honor', value: 1 }],
              effects: [
                { type: 'changeStat', key: 'honor', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.orangery.calledSubmission', value: true },
              ],
              nextNodeId: 'thorn-orangery-6-call-submission',
            },
            {
              id: 'thorn-orangery-5-see-endurance',
              text: 'Почути в ній не слабкість, а страшну дорослу витривалість.',
              effects: [
                { type: 'changeStat', key: 'altruism', delta: 1 },
                { type: 'changeStat', key: 'restraint', delta: 1 },
                { type: 'changeMeta', key: 'morale', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.orangery.sawEndurance', value: true },
              ],
              nextNodeId: 'thorn-orangery-6-see-endurance',
            },
            {
              id: 'thorn-orangery-5-leave-fracture',
              text: 'Не вирішувати зараз нічого. Просто піти з цією тріщиною в собі.',
              conditions: [{ type: 'statGte', key: 'machiavellianism', value: 1 }],
              effects: [
                { type: 'changeStat', key: 'machiavellianism', delta: 1 },
                { type: 'changeStat', key: 'paranoia', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.orangery.leftFractured', value: true },
              ],
              nextNodeId: 'thorn-orangery-6-leave-fracture',
            },
            {
              id: 'thorn-orangery-5-ask-what-remains',
              text: '«Якщо це твоя форма виживання, то що в ній лишилося твоїм?»',
              conditions: [{ type: 'statGte', key: 'pragmatism', value: 1 }],
              effects: [
                { type: 'changeStat', key: 'pragmatism', delta: 1 },
                { type: 'changeStat', key: 'honor', delta: 1 },
                { type: 'setFlag', flagId: 'chapter1.thorn.orangery.askedWhatRemains', value: true },
              ],
              nextNodeId: 'thorn-orangery-6-ask-what-remains',
            },
          ],
        },
        'thorn-orangery-6-call-submission': {
          id: 'thorn-orangery-6-call-submission',
          type: 'dialogue',
          speakerId: 'lady-sera',
          emotion: 'hard',
          text: 'Назви це покорою, якщо тобі так легше. Але коли падає стеля, кричати про честь зазвичай починають ті, хто ніколи не тримав її руками.',
          nextNodeId: 'thorn-orangery-7',
        },
        'thorn-orangery-6-see-endurance': {
          id: 'thorn-orangery-6-see-endurance',
          type: 'dialogue',
          speakerId: 'lady-sera',
          emotion: 'tired',
          text: 'Я не рятую цей дім, Мірелло. Я лише намагаюся лишити в ньому кілька місць, де він не зламає тебе раніше, ніж ти навчишся ходити сама.',
          nextNodeId: 'thorn-orangery-7',
        },
        'thorn-orangery-6-leave-fracture': {
          id: 'thorn-orangery-6-leave-fracture',
          type: 'dialogue',
          speakerId: 'lady-sera',
          emotion: 'calm',
          text: 'Коли перестанеш шукати тут чистих дорослих, повернися. Тоді нам буде про що говорити чесніше.',
          nextNodeId: 'thorn-orangery-7',
        },
        'thorn-orangery-6-ask-what-remains': {
          id: 'thorn-orangery-6-ask-what-remains',
          type: 'dialogue',
          speakerId: 'lady-sera',
          emotion: 'calm',
          text: 'Мої рішення. Не всі. Але ще мої. Інколи цього досить, щоб не стати просто чужим наслідком.',
          nextNodeId: 'thorn-orangery-7',
        },
        'thorn-orangery-7': {
          id: 'thorn-orangery-7',
          type: 'narration',
          text: 'На виході з оранжереї Мірелла вже знала головне: дорослі в цьому домі відрізнялися не чистотою, а способом, у який домовлялися з брудом. І одного дня їй доведеться обирати не між добрим і поганим, а між різними цінами за власне обличчя.',
          onEnterEffects: [
            { type: 'setFlag', flagId: 'chapter1.thorn.departure.completed', value: true },
          ],
          isEnd: true,
        },
      },
    },

    [chapter1ThornDepartureCorsetTieReplayScene.id]: chapter1ThornDepartureCorsetTieReplayScene,
    [chapter1ThornDepartureFatherBetrayalReplayScene.id]:
      chapter1ThornDepartureFatherBetrayalReplayScene,
  },
} satisfies SceneGenerationDocument;
