import type { TravelBoardData } from '@engine/types/travel';

export const chapter1UndergroundRouteBoard: TravelBoardData = {
  id: 'chapter-1/travel/underground-route',
  title: 'Underground Route',
  chapterId: 'chapter-1',
  description:
    'A broken route from the black river temple toward the outer roads. Roll, choose a branch, and survive what waits at the final stop.',
  backgroundId: 'chapter-1/backgrounds/ancient-temple-black-river.webp',
  startNodeId: 'temple-threshold',
  scoutCharges: 1,
  scoutDepth: 3,
  nodes: {
    'temple-threshold': {
      id: 'temple-threshold',
      x: 10,
      y: 52,
      type: 'empty',
      title: 'Temple Threshold',
      description: 'Cold stone, broken idols, and the first way out.',
      nextNodeIds: ['black-river-ledger'],
    },
    'black-river-ledger': {
      id: 'black-river-ledger',
      x: 24,
      y: 52,
      type: 'empty',
      title: 'Black River Ledger',
      description: 'The path narrows before a split in the drowned passage.',
      nextNodeIds: ['forked-passage'],
    },
    'forked-passage': {
      id: 'forked-passage',
      x: 39,
      y: 52,
      type: 'question',
      title: 'Forked Passage',
      description: 'The walls whisper. One branch smells of iron, the other of dust.',
      nextNodeIds: ['shackled-guard', 'buried-cache'],
      eventRefId: 'chapter1.travel.forkedWhisper',
    },
    'shackled-guard': {
      id: 'shackled-guard',
      x: 57,
      y: 31,
      type: 'battle',
      title: 'Shackled Guard',
      description: 'A road guard, half-lost and still violent, blocks the upper route.',
      nextNodeIds: ['healing-spring'],
      hidden: true,
      oneTime: true,
      battleTemplateId: 'guard-battle',
    },
    'buried-cache': {
      id: 'buried-cache',
      x: 57,
      y: 72,
      type: 'loot',
      title: 'Buried Cache',
      description: 'Someone hid a satchel under cracked support beams.',
      nextNodeIds: ['needle-arch'],
      hidden: true,
      oneTime: true,
      itemId: 'basic-potion',
      itemQuantity: 1,
      onResolveEffects: [
        {
          type: 'setFlag',
          flagId: 'chapter1.travel.foundCache',
          value: true,
        },
      ],
    },
    'healing-spring': {
      id: 'healing-spring',
      x: 73,
      y: 31,
      type: 'heal',
      title: 'Healing Spring',
      description: 'Warm mineral water pools between ancient machine roots.',
      nextNodeIds: ['collapsed-camp'],
      hidden: true,
      oneTime: true,
      onResolveEffects: [
        {
          type: 'restoreResource',
          resource: 'hp',
          amount: 18,
          targetScope: 'party',
        },
      ],
    },
    'needle-arch': {
      id: 'needle-arch',
      x: 73,
      y: 72,
      type: 'trap',
      title: 'Needle Arch',
      description: 'A lattice of rusted needles snaps from the stonework.',
      nextNodeIds: ['collapsed-camp'],
      hidden: true,
      oneTime: true,
      onResolveEffects: [
        {
          type: 'changeMeta',
          key: 'morale',
          delta: -1,
        },
        {
          type: 'setFlag',
          flagId: 'chapter1.travel.needleTrapTriggered',
          value: true,
        },
      ],
    },
    'collapsed-camp': {
      id: 'collapsed-camp',
      x: 84,
      y: 52,
      type: 'rest',
      title: 'Collapsed Camp',
      description: 'A dry pocket of stone offers a short but precious pause.',
      nextNodeIds: ['whisper-wall'],
      hidden: true,
      oneTime: true,
      onResolveEffects: [
        {
          type: 'restoreResource',
          resource: 'hp',
          amount: 10,
          targetScope: 'party',
        },
        {
          type: 'restoreResource',
          resource: 'mana',
          amount: 6,
          targetScope: 'party',
        },
        {
          type: 'changeMeta',
          key: 'morale',
          delta: 1,
        },
      ],
    },
    'whisper-wall': {
      id: 'whisper-wall',
      x: 93,
      y: 52,
      type: 'story',
      title: 'Whisper Wall',
      description: 'Old words peel from the masonry as something beneath the river answers.',
      nextNodeIds: ['iron-gate'],
      hidden: true,
      oneTime: true,
      dialogueId: 'chapter-1/dialogues/awakening',
    },
    'iron-gate': {
      id: 'iron-gate',
      x: 99,
      y: 52,
      type: 'exit',
      title: 'Iron Gate',
      description: 'Beyond the broken gate, the route opens back into the outer world.',
      nextNodeIds: [],
      hidden: true,
      oneTime: true,
      onResolveEffects: [
        {
          type: 'setFlag',
          flagId: 'chapter1.travel.undergroundRouteCleared',
          value: true,
        },
        {
          type: 'changeLocation',
          locationId: 'pilgrim-road',
          nodeId: 'city-gate',
        },
      ],
    },
  },
};
